name: Deploy Release Docs
on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    name: Deploy release documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up rye
        uses: eifinger/setup-rye@v3
      - name: Update Rye
        run: |
          rye self update
      - name: Sync dependencies using rye
        run: |
          rye config --set-bool behavior.use-uv=true
          rye pin 3.12
          rye sync
      - name: Set up build cache
        uses: actions/cache@v4
        id: cache
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # derived from:
      # https://github.com/RemoteCloud/public-documentation/blob/dev/.github/workflows/build_docs.yml
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Set release notes tag
        run: |
          export TAG_PATH=${{ github.ref }}
          echo ${TAG_PATH}
          echo "TAG_VERSION=${TAG_PATH##*/}" >> $GITHUB_ENV
          echo ${TAG_VERSION}
      - name: Deploy documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git fetch origin gh-pages --depth=1
          rye run mike deploy --update-alias --push ${TAG_VERSION} latest
